### ISSUE TITLE
Create a basic workflow for testing

### ISSUE THREAD

**Issue by abhi18av** [bioinformatics-lab/k8s_test_nf#1]
1. Download genomes using fromSRA
2. Run FastQC on them
3. Run MultiQC on them
4. Publish the MultiQC report

**Comment by abhi18av** [comment]
Once this is done, then we can start testing `staging` new files and `publishing` results.

**Comment by Mxrcon** [comment]
@abhi18av I've just finished my first scratch for the workflow, i added two profiles, one for downloading files using SRA and other to using files located on the folder of the execution, i called them `sra` and `local`, what do you think about it? I've run it on my computer and it seems perfectly fine, maybe we can test it!

**Comment by abhi18av** [comment]
Hi @Mxrcon , yeah looks good to go ahead.

Just one change, try to use only 3 genomes.

**Comment by abhi18av** [comment]
The success would be that you are able to publish the multiqc file in a location.

We might only be able to verify it via logging into the server via SSH - no worries about that. Let me know when you'd like me to confirm.

Also, closing this issue since the workflow draft is done.

**Comment by Mxrcon** [comment]
@abhi18av Ok! i'll use only 3 genomes, lets proceed with the testings? I'll launch them using tower, but i'd like that you setup the local files for the `local` profile, I'll launch it now with my NCBI key for `sra.`
